spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    sql-format: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/events?currentSchema=afisha
    driver-class-name: org.postgresql.Driver
server:
  port: 80
url:
  urlClassifierCountry: http://localhost:8081/api/v1/classifier/country/check/
  urlClassifierCategory: http://localhost:8081/api/v1/classifier/concert/check/