FROM openjdk:11-jdk-slim
MAINTAINER Uladzimir

COPY target/classifier_service-1.0.0-SNAPSHOT.jar classifier_service-1.0.0-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/classifier_service-1.0.0-SNAPSHOT.jar"]
